import type { HolidayEvent } from './events';
import { getChristmasQuotes } from './localizedQuotes';

export const eventQuotes: Record<HolidayEvent, string[]> = {
  christmas: getChristmasQuotes('en'),
  diwali: [
    "Let this Diwali burn all your bad times and light up the bright future.",
    "Diwali is the festival of lights, but it is also a festival of relationships.",
    "May the light of Diwali fill your life with happiness and prosperity.",
    "This Diwali, let us light the lamp of love, compassion, and kindness.",
    "Deepavali is a reminder that light always prevails over darkness.",
    "Wishing you a Diwali filled with sparkling lights, warm memories, and sweet moments.",
    "The glow of diyas, the sweetness of sweets, and the warmth of family - that's Diwali.",
    "May your life be as colorful as rangoli and as bright as diyas this Diwali.",
    "Diwali is not just about lighting lamps, it's about lighting hearts.",
    "Celebrate the victory of light over darkness and good over evil.",
    "May millions of lamps illuminate your life with endless joy and prosperity.",
    "Diwali is the time to shine both inside and out.",
    "Let the festival of lights brighten your heart and home.",
    "The best Diwali decoration is a smiling face.",
    "May your Diwali be filled with moments of love, laughter, and light."
  ],
  easter: [
    "Easter is the demonstration that love is stronger than death.",
    "The resurrection gives my life meaning and direction.",
    "Easter is meant to be a symbol of hope, renewal, and new life.",
    "Let the Easter joy fill your heart with peace and happiness.",
    "Easter says you can put truth in a grave, but it won't stay there.",
    "Spring is nature's way of saying, 'Let's party!' - and Easter is the cherry on top.",
    "The story of Easter is the story of God's wonderful window of divine surprise.",
    "Easter is the time to rejoice and be grateful for the gift of life.",
    "May your Easter be filled with precious moments and warm memories.",
    "Easter spells out one word: hope.",
    "The best message of Easter is hope - hope for a new beginning.",
    "Easter is a time to open our hearts to the light of love.",
    "Let every sunrise remind you of the promise of a new beginning.",
    "Easter is the season to bloom with joy and gratitude.",
    "May the miracle of Easter bring you renewed hope and faith."
  ],
  eid_al_fitr: [
    "Eid Mubarak! May your life be filled with happiness and peace.",
    "The beauty of Eid lies in sharing and caring for each other.",
    "Eid is a day of joy, blessings, and gratitude for all that we have.",
    "May the blessings of Allah be with you today and always.",
    "Eid Mubarak! Wishing you and your family a wonderful celebration.",
    "Let the spirit of Eid fill your heart with love and compassion.",
    "Eid is the reward for a month of patience and devotion.",
    "May this Eid bring you closer to your loved ones and to your faith.",
    "Celebrate Eid with an open heart and a grateful soul.",
    "Eid is not just a celebration, it's a feeling of togetherness.",
    "Wishing you peace, happiness, and divine blessings on this auspicious day.",
    "The best Eids are spent with family, sharing food and laughter.",
    "May the joy of Eid stay in your heart throughout the year.",
    "Eid reminds us that generosity and kindness are the greatest gifts.",
    "From our family to yours, Eid Mubarak!"
  ],
  fourth_of_july: [
    "Freedom is never more than one generation away from extinction.",
    "Land of the free, because of the brave.",
    "America was not built on fear. America was built on courage, imagination, and an unbeatable determination.",
    "Let freedom ring from every hill and molehill of America.",
    "Freedom is the open window through which pours the sunlight of the human spirit.",
    "Those who deny freedom to others deserve it not for themselves.",
    "Where liberty dwells, there is my country.",
    "The essence of America is the celebration of diversity and freedom.",
    "Liberty is the breath of life to nations.",
    "Freedom lies in being bold.",
    "America is a tune. It must be sung together.",
    "The American flag is a symbol of our nation's strength and unity.",
    "This land was made for you and me.",
    "Celebrate the spirit of independence and the joy of freedom.",
    "May the stars and stripes forever wave over the land of the free."
  ],
  halloween: [
    "When black cats prowl and pumpkins gleam, may luck be yours on Halloween.",
    "Double, double toil and trouble; fire burn and cauldron bubble.",
    "There is magic in the night when the moon shines bright on Halloween.",
    "Every day is Halloween in a world full of ghosts and goblins.",
    "Be afraid... be very afraid... of how much candy you might eat!",
    "On Halloween, witches come out to play — but so do the candy bars!",
    "I'm just here for the candy.",
    "Halloween is the one night a year when we can truly be anything we want.",
    "Creep it real this Halloween.",
    "The only thing we have to fear is fear itself... and maybe ghosts.",
    "Sleep with one eye open tonight.",
    "Halloween is not just a holiday, it's a state of mind.",
    "Witchful thinking: may all your Halloween wishes come true.",
    "Some ghouls just want to have fun.",
    "Eat, drink, and be scary."
  ],
  hanukkah: [
    "A little bit of light dispels a lot of darkness.",
    "Hanukkah is the festival of lights, but it is also the festival of hope.",
    "Just as a single candle can light a thousand others, so too can one act of kindness.",
    "The miracle of Hanukkah is not the oil that lasted eight days, but the courage to keep believing.",
    "May the lights of Hanukkah guide you through even the darkest times.",
    "Hanukkah teaches us that even a small amount of light can overcome great darkness.",
    "Blessed is the match that is consumed in kindling the light.",
    "Hanukkah is a reminder that hope never dies.",
    "Eight nights of light, eight nights of wonder, eight nights of miracles.",
    "The menorah reminds us that light always overcomes darkness.",
    "May the glow of the menorah fill your home with warmth and joy.",
    "Hanukkah: a festival of faith, family, and fried food!",
    "A happy heart is like a menorah, shining light in all directions.",
    "Let every candle remind you of the power of faith and perseverance.",
    "The miracle of light continues to shine in each of our hearts."
  ],
  new_year: [
    "New year, new beginnings, new hopes, new dreams.",
    "Write it on your heart that every day is the best day of the year.",
    "Cheers to a new year and another chance for us to get it right.",
    "The secret of getting ahead is getting started.",
    "Tomorrow is the first blank page of a 365-page book. Write a good one.",
    "New year — a new chapter, new verse, or just the same old story? We get to write it.",
    "This year, be your own kind of beautiful.",
    "For last year's words belong to last year's language, and next year's words await another voice.",
    "The best is yet to come.",
    "Your future is created by what you do today, not tomorrow.",
    "Year's end is neither an end nor a beginning but a going on.",
    "Make it a year of progress, not perfection.",
    "Every moment is a fresh beginning.",
    "This year, let your dreams be bigger than your fears.",
    "May your coming year be filled with magic and dreams."
  ],
  st_patricks_day: [
    "May the luck of the Irish be with you today and always.",
    "May your blessings outnumber the shamrocks that grow.",
    "St. Patrick's Day is a day to celebrate the luck of the Irish.",
    "May your pockets be heavy and your heart be light.",
    "There is no language like the Irish for soothing and quieting.",
    "May the road rise up to meet you, may the wind be always at your back.",
    "The beauty of the emerald isle is felt in every heart on this day.",
    "Everyone is Irish on St. Patrick's Day!",
    "May you live as long as you want, and never want as long as you live.",
    "May your troubles be less and your blessings be more.",
    "Find a reason to smile and spread the Irish cheer.",
    "Dance like nobody's watching, even if you don't know the jig.",
    "St. Patrick's Day is a celebration of Irish heritage and happiness.",
    "May your day be touched with a bit of Irish luck.",
    "Green is the color of hope, and today we celebrate with hope and joy."
  ],
  thanksgiving: [
    "Gratitude is the heart's memory.",
    "Thanksgiving is a time of togetherness and gratitude.",
    "Give thanks for a little and you will find a lot.",
    "Gratitude turns what we have into enough.",
    "Thanksgiving is one of my favorite days of the year because it reminds us to be grateful.",
    "The spirit of Thanksgiving is about counting blessings, not calories.",
    "Be thankful for what you have; you'll end up having more.",
    "There is always, always, always something to be thankful for.",
    "Thanksgiving is the holiday of the open heart.",
    "Gratitude is the fairest blossom which springs from the soul.",
    "Let us remember that the Thanksgiving spirit is about sharing and caring.",
    "Family, food, and gratitude — the perfect recipe for Thanksgiving.",
    "Thanksgiving is a reminder that we are surrounded by blessings.",
    "The more you give thanks, the more you receive to be thankful for.",
    "Coming together is a beginning, staying together is progress, and working together is success."
  ],
  valentines_day: [
    "Love is composed of a single soul inhabiting two bodies.",
    "Where there is love there is life.",
    "The best thing to hold onto in life is each other.",
    "Love is not about how many days, months, or years you've been together. Love is about how much you love each other every day.",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
    "Love is the poetry of the senses.",
    "To love and be loved is to feel the sun from both sides.",
    "In all the world, there is no heart for me like yours.",
    "Love is made of two hearts that beat as one.",
    "The greatest happiness of life is the conviction that we are loved.",
    "Love doesn't make the world go round. Love is what makes the ride worthwhile.",
    "A true friend knows your weaknesses but shows you your strengths.",
    "Love is the master key that opens the gates of happiness.",
    "I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love.",
    "The only thing we never get enough of is love."
  ]
};

export function getEventQuotes(event: HolidayEvent, language: string): string[] {
  if (event === 'christmas') {
    return getChristmasQuotes(language);
  }
  return eventQuotes[event];
}
